language: java

jobs:
  include:
    - os: linux
      dist: focal
      jdk: openjdk11
      script: make graphblas-java
    - os: osx
      osx_image: xcode12.2
      jdk: openjdk11
      script: make graphblas-java




cache:
  directories:
  - $HOME/.m2
