language: java

jobs:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
      install: true
      script: make all
    - os: osx
      osx_image: xcode12.2
      jdk: openjdk11
      install: true
      script: make all

cache:
  directories:
  - $HOME/.m2

